### ISSUE TITLE
Doesn't instantiate as root

### ISSUE THREAD

**Issue by paultrost** [paultrost/Disk-SMART-Perl#3]
# cat test.pl
#!/usr/bin/perl
use warnings;
use strict;
use Disk::SMART;
my $new = Disk::SMART->new;

# perl test.pl
Smartctl couldn't poll device 0
 at test.pl line 6.

Instantiates fine when run with sudo

**Comment by teodesian** [comment]
die('not running as root') if $<;

**Comment by paultrost** [comment]
Corrected in 0.15 to now die if executing user isn't root. Apparently my issue with "couldn't poll device 0" had to do with a duplicate copy of the module in /root.
